### ISSUE TITLE
[Request] Use Recalbox EmulationStation instead of vanilla ES

### ISSUE THREAD

**Issue by C-Fu** [mcobit/retropie-osmc#2]
Good day,

From what I've tried and seen, Recalbox's fork of EmulationStation has more features than the current "official" version of ES, such as
- joystick config in ES will automagically map the buttons in retroarch/retropie
- bg music for each and every console rom menu
- sound setup direct from ES
- auto update retroarch+es directly from the menu

https://github.com/digitallumberjack/recalbox-emulationstation
https://github.com/digitalLumberjack/recalbox-os

**Comment by mcobit** [comment]
Hi. The only thing that I am doing here is installing Retro Pie. Please suggest it to the developers of Retropie as I do not intend to maintain a separate fork of Retro Pie.

**Comment by C-Fu** [comment]
Ah, ok. No worries, just stating my experience that's all. Cheers for the great work!
